[versions]
agp = "9.1.0"
googleServices = "4.4.2"
firebaseBom = "33.7.0"

[libraries]
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.15.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
